ignore:
  - "*.pl.md"

nav:
  - "SOLUTIONS*.md"
  - "CAPABILITY-MATRIX*.md"
  - "CAPABILITY-REGISTRY*.md"
  - "capability-advertisement.md"
  - "node.md"
  - "node-ui.md"
  - "ferment.md"
  - "whisper.md"
  - "anon.md"
  - "raw-signal-access.md"
