nav:
  - PL:
      - Supplementary: pl/SUPPLEMENTARY.pl.md
      - Ontological Basis: pl/ONTOLOGICAL-BASIS.pl.md
  - EN:
      - Supplementary: en/SUPPLEMENTARY.en.md
      - Ontological Basis: en/ONTOLOGICAL-BASIS.en.md
  - CS:
      - Ontological Basis: cs/ONTOLOGICAL-BASIS.cs.md
