nav:
  - PL:
      - Supplementary: pl/SUPPLEMENTARY.pl.md
      - Ontological Basis: pl/ONTOLOGICAL-BASIS.pl.md
      - Ekonomia sprawczej wzajemności: pl/ECONOMY-OF-AGENTIC-MUTUALITY.pl.md
  - EN:
      - Supplementary: en/SUPPLEMENTARY.en.md
      - Ontological Basis: en/ONTOLOGICAL-BASIS.en.md
      - Economy of Agentic Mutuality: en/ECONOMY-OF-AGENTIC-MUTUALITY.en.md
  - CS:
      - Ontological Basis: cs/ONTOLOGICAL-BASIS.cs.md
      - Ekonomika aktérské vzájemnosti: cs/ECONOMY-OF-AGENTIC-MUTUALITY.cs.md
