#!/usr/bin/env python3

from __future__ import annotations

import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCHEMAS_DIR = ROOT / "doc" / "schemas"
EXAMPLES_DIR = SCHEMAS_DIR / "examples"
INVALID_EXAMPLES_DIR = EXAMPLES_DIR / "invalid"
GOLDEN_DIR = SCHEMAS_DIR / "golden"
NODE_WORKSPACE_SENTINELS = (
    Path("Cargo.toml"),
    Path("protocol/Cargo.toml"),
    Path("schema-gate/Cargo.toml"),
)

SCHEMA_WHITELIST = (
    "node-identity.v1.schema.json",
    "node-advertisement.v1.schema.json",
    "node-succession.v1.schema.json",
    "peer-handshake.v1.schema.json",
    "capability-advertisement.v1.schema.json",
    "capability-passport-present.v1.schema.json",
    "capability-passport-revocation.v1.schema.json",
    "capability-passport.v1.schema.json",
    "capability-proof-presentation-batch.v1.schema.json",
    "capability-authorization-policy.v1.schema.json",
    "seed-capability-registration.v1.schema.json",
    "federation-root.v1.schema.json",
    "federation-service-endorsement.v1.schema.json",
    "federation-service-endorsement-revocation.v1.schema.json",
    "seed-directory-query-attestation.v1.schema.json",
    "capability-schema-present.v1.schema.json",
    "capability-schema.v1.schema.json",
    "signal-marker-envelope.v1.schema.json",
    "signal-marker.v1.schema.json",
    "coi-declaration.v1.schema.json",
    "exception-record.v1.schema.json",
    "emergency-signal.v1.schema.json",
    "reputation-signal.v1.schema.json",
    "agora-authority-policy.v1.schema.json",
    "agora-public-rejection.v1.schema.json",
    "reputation-snapshot.v1.schema.json",
    "nym-certificate.v1.schema.json",
    "nym-authorship-proof.v1.schema.json",
    "nym-succession.v1.schema.json",
    "association-room-proposal.v1.schema.json",
    "room.v1.schema.json",
    "room-membership.v1.schema.json",
    "room-event.v1.schema.json",
    "room-policy.v1.schema.json",
    "room-live-message.v1.schema.json",
    "room-live-message.v2.schema.json",
    "room-access-denial.v1.schema.json",
    "room-floor-policy.v1.schema.json",
    "room-floor-lease.v1.schema.json",
    "room-moderation-intent.v1.schema.json",
    "room-moderation-audit.v1.schema.json",
    "room-relay-endpoint.v1.schema.json",
    "room-relay-delivery.v1.schema.json",
    "room-relay-sender-key-distribution.v1.schema.json",
    "room-relay-sealed-delivery.v1.schema.json",
    "room-membership-attestation.v1.schema.json",
    "room-membership-attestation-request.v1.schema.json",
    "room-attestation-audit.v1.schema.json",
    "whisper-interest.v1.schema.json",
    "whisper-signal.v1.schema.json",
    "whisper-trace.v1.schema.json",
    "whisper-trace-consent-request.v1.schema.json",
    "whisper-trace-publish-request.v1.schema.json",
    "whisper-trace-publish-result.v1.schema.json",
    "whisper-threshold-reached.v1.schema.json",
    "weak-signal-finding.v1.schema.json",
    "whisper-redaction-prepare-request.v1.schema.json",
    "whisper-redaction-prepare-response.v1.schema.json",
    "procurement-offer.v1.schema.json",
    "procurement-contract.v1.schema.json",
    "procurement-receipt.v1.schema.json",
    "gateway-policy.v1.schema.json",
    "escrow-policy.v1.schema.json",
    "settlement-policy-disclosure.v1.schema.json",
    "ledger-account.v1.schema.json",
    "gateway-receipt.v1.schema.json",
    "community-pool-disbursement.v1.schema.json",
    "participant-bind.v1.schema.json",
    "participant-capability-limits.v1.schema.json",
    "node-operator-binding.v1.schema.json",
    "client-instance-attachment.v1.schema.json",
    "client-instance-detachment.v1.schema.json",
    "client-instance-recovery.v1.schema.json",
    "peer-status.v1.schema.json",
    "question-envelope.v1.schema.json",
    "response-envelope.v1.schema.json",
    "service-offer.v1.schema.json",
    "service-offer-relay.v1.schema.json",
    "topic-taxonomy.v1.schema.json",
    "topic-resolution.v1.schema.json",
    "corpus-reasoning-query.v1.schema.json",
    "corpus-reasoning-bid.v1.schema.json",
    "corpus-reasoning-answer.v1.schema.json",
    "corpus-reasoning-bid-state.v1.schema.json",
    "corpus-reasoning-chair-control-policy.v1.schema.json",
    "corpus-reasoning-room-policy.v1.schema.json",
    "corpus-reasoning-room-policy.v2.schema.json",
    "corpus-reasoning-room-invite.v1.schema.json",
    "corpus-reasoning-turn-proposal.v1.schema.json",
    "corpus-reasoning-role-assignment.v1.schema.json",
    "corpus-reasoning-instruction-overlay.v1.schema.json",
    "service-order.v1.schema.json",
    "offer-catalog-fetch-request.schema.json",
    "offer-catalog-fetch-response.schema.json",
    "classification.v1.schema.json",
    "memarium-host-api.v1.schema.json",
    "memarium-blob.v1.schema.json",
    "artifact-delivery-envelope.v1.schema.json",
    "artifact-delivery-result.v1.schema.json",
    "artifact-delivery-status.v1.schema.json",
    "artifact-object-pointer.v1.schema.json",
    "middleware-channel-hello.v1.schema.json",
    "middleware-channel-accepted.v1.schema.json",
    "middleware-channel-frame.v1.schema.json",
    "middleware-channel-host-capability-call.v1.schema.json",
    "middleware-channel-call-result.v1.schema.json",
    "middleware-channel-request-cancel.v1.schema.json",
    "middleware-channel-heartbeat.v1.schema.json",
    "middleware-channel-session-shutdown.v1.schema.json",
    "middleware-module-http-request.v1.schema.json",
    "middleware-module-http-response.v1.schema.json",
    "deferred-operation.v1.schema.json",
    "deferred-operation-status.v1.schema.json",
    "interaction-broker-watch.v1.schema.json",
    "interaction-broker-wait.request.v1.schema.json",
    "interaction-broker-wait.outcome.v1.schema.json",
    "interaction-broker-probe.v1.schema.json",
    "operator-consent.request.v1.schema.json",
    "operator-consent-decision.v1.schema.json",
    "operator-consent-binding.v1.schema.json",
    "sensorium-workbench.consent-descriptor.v1.schema.json",
    "sensorium-os.consent-descriptor.v1.schema.json",
    "sensorium-os.action-catalog-delta.v1.schema.json",
    "sensorium-os.action-catalog-sidecar.v1.schema.json",
    "sensorium-relative-path-address.v1.schema.json",
    "sensorium-command-profile.v1.schema.json",
    "sensorium-command-intent.v1.schema.json",
    "sensorium-pty-resource-caps.v1.schema.json",
    "sensorium-workbench-environment.v1.schema.json",
    "sensorium-virt-backend-capabilities.v1.schema.json",
    "sensorium-virt-environment-plan.v1.schema.json",
    "sensorium-virt-image-manifest.v1.schema.json",
    "sensorium-virt-recovery-record.v1.schema.json",
    "sensorium-virt-guest-frame.v1.schema.json",
    "sensorium-virt.host.request.v1.schema.json",
    "sensorium-virt-vfkit-deployment-report.v1.schema.json",
    "sensorium-virt-cloud-hypervisor-deployment-report.v1.schema.json",
    "story-012-vfkit-full-system-report.v1.schema.json",
    "sensorium-terminal-session.v1.schema.json",
    "sensorium-terminal-command.v1.schema.json",
    "sensorium-terminal-input.v1.schema.json",
    "sensorium-terminal-event.v1.schema.json",
    "sensorium-interface-remote-feed-request.v1.schema.json",
    "sensorium-terminal-screen-snapshot.v1.schema.json",
    "sensorium-file-snapshot.v1.schema.json",
    "sensorium-file-read-result.v1.schema.json",
    "sensorium-workbench-patch.v1.schema.json",
    "sensorium-workbench-patch-apply-result.v1.schema.json",
    "sensorium-workbench-patch-stage-result.v1.schema.json",
    "sensorium-workbench-outcome.v1.schema.json",
    "sensorium-workbench-error-codes.v1.schema.json",
    "sensorium-operational-context.v1.schema.json",
    "sensorium-interface-resource.v1.schema.json",
    "sensorium-interface-descriptor.v1.schema.json",
    "sensorium-interface-actuation-descriptor.v1.schema.json",
    "sensorium-interface-actuation-status.v1.schema.json",
    "sensorium-interface-control-request.v1.schema.json",
    "sensorium-interface-control-status.v1.schema.json",
    "sensorium-interface-control-lease.v1.schema.json",
    "sensorium-interface-actuation-grant-scope.v1.schema.json",
    "sensorium-interface-invoke-request.v1.schema.json",
    "sensorium-interface-invoke-receipt.v1.schema.json",
    "sensorium-interface-terminal-input.v1.schema.json",
    "sensorium-interface-terminal-resize.v1.schema.json",
    "sensorium-interface-terminal-signal.v1.schema.json",
    "sensorium-interface-led-set.v1.schema.json",
    "sensorium-interface-frame.v1.schema.json",
    "sensorium-interface-read-request.v1.schema.json",
    "sensorium-interface-read-result.v1.schema.json",
    "sensorium-interface-status.v1.schema.json",
    "sensorium-interface-subscribe-request.v1.schema.json",
    "sensorium-interface-subscription-command.v1.schema.json",
    "sensorium-interface-subscription-status.v1.schema.json",
    "vendor-media-type-registry.v1.schema.json",
    "inquirium.model-package.manifest.v1.schema.json",
    "inquirium.model-package.source-trust.v1.schema.json",
    "inquirium.model-package.operator-endorsement.v1.schema.json",
    "inquirium.model-package.install-receipt.v1.schema.json",
    "inquirium.model-package.active-profile.v1.schema.json",
    "inquirium.model-package.install-plan.v1.schema.json",
    "inac-control.v1.schema.json",
    "notification.v1.schema.json",
    "notification-create.v1.schema.json",
    "notification-action.v1.schema.json",
    "notification-action-result.v1.schema.json",
    "notification-state-changed.v1.schema.json",
    "notification-allow.v1.schema.json",
    "notification-delivery-policy.v1.schema.json",
    "local-contact.v1.schema.json",
    "contact-claim.v1.schema.json",
    "contact-lookup-result.v1.schema.json",
    "contact-request.v1.schema.json",
    "contact-attestation-request.v1.schema.json",
    "contact-attestation-result.v1.schema.json",
    "membership-invitation.v1.schema.json",
    "membership-sponsorship.v1.schema.json",
    "membership-acceptance.v1.schema.json",
    "participant-entry-profile.v1.schema.json",
    "participant-effective-limits.v1.schema.json",
    "surface-access-policy.v1.schema.json",
    "message-envelope.v1.schema.json",
    "messaging.passport-issued.v1.schema.json",
    "messaging.passport-revoked.v1.schema.json",
    "messaging.retention-decided.v1.schema.json",
    "messaging.crisis-marked.v1.schema.json",
    "capability-passport-lookup.v1.schema.json",
    "local-recipient-mailbox-resolve.v1.schema.json",
    "service-ca-material.v1.schema.json",
    "service-ca-revocation.v1.schema.json",
    "causal-context.v1.schema.json",
    "execution-receipt.v1.schema.json",
    "replication-summary.v1.schema.json",
    "replication-delta-request.v1.schema.json",
    "replication-delta-batch.v1.schema.json",
    "replication-apply-report.v1.schema.json",
    "scoped-claim-request.v1.schema.json",
    "scoped-claim-presentation.v1.schema.json",
    "scoped-claim-type-registry.v1.schema.json",
    "trace-event.v1.schema.json",
    "trace-link.v1.schema.json",
)

EXAMPLE_WHITELIST = (
    "bootstrap.node-identity.json",
    "seed-wss.node-advertisement.json",
    "vector-signed.node-advertisement.json",
    "basic.node-succession.json",
    "bootstrap.hello.peer-handshake.json",
    "bootstrap.ack.peer-handshake.json",
    "base-node.capability-advertisement.json",
    "network-ledger.capability-passport-present.json",
    "sealer-access.capability-passport-present.json",
    "memarium-space-access.capability-passport-present.json",
    "offer-catalog.seed-capability-registration.json",
    "orbiplex-main.federation-root.json",
    "org-threshold.federation-root.json",
    "bootstrap-inline-endorsement.federation-root.json",
    "seed-directory.federation-service-endorsement.json",
    "seed-directory.federation-service-endorsement-revocation.json",
    "mixed.capability-proof-presentation-batch.json",
    "capability.seed-directory-query-attestation.json",
    "memarium-declassify.capability-passport-present.json",
    "community-key-access.capability-passport-present.json",
    "p071-workbench.capability-authorization-policy.json",
    "audio-transcription.capability-schema-present.json",
    "audio-transcription.capability-schema.json",
    "participant-broadcast.signal-marker-envelope.json",
    "privacy-redacted.signal-marker.json",
    "no-conflict.coi-declaration.json",
    "temporary-routing-override.exception-record.json",
    "blackout-failover.exception-record.json",
    "blackout-correlated.emergency-signal.json",
    "degraded-trust-peer-corroborated.emergency-signal.json",
    "participant-governance-inaction.reputation-signal.json",
    "node-relay-unreliable.reputation-signal.json",
    "nym-helpful-participation.reputation-signal.json",
    "default.agora-authority-policy.json",
    "public-policy-denial.agora-public-rejection.json",
    "community-trusted.reputation-snapshot.json",
    "selected-responder.question-envelope.json",
    "single-responder.procurement-offer.json",
    "contract-without-receipt.response-envelope.json",
    "host-ledger-escrow.procurement-contract.json",
    "arbiter-confirmed.procurement-contract.json",
    "host-ledger-settled.procurement-receipt.json",
    "arbiter-confirmed.procurement-receipt.json",
    "pl-main.gateway-policy.json",
    "pl-main.escrow-policy.json",
    "gateway-payout-freeze.settlement-policy-disclosure.json",
    "access-condition-violation.settlement-policy-disclosure.json",
    "prepaid-participant.ledger-account.json",
    "community-pool.ledger-account.json",
    "inbound-topup.gateway-receipt.json",
    "ubc-subsidy.community-pool-disbursement.json",
    "bound-over-live-session.participant-bind.json",
    "limited-procurement-offer.participant-capability-limits.json",
    "primary-operator.node-operator-binding.json",
    "operator-remote-screen.client-instance-attachment.json",
    "user-requested.client-instance-detachment.json",
    "replace-device.client-instance-recovery.json",
    "warm.peer-status.json",
    "federation-local-procurement.question-envelope.json",
    "federation-local-pseudonymous.question-envelope.json",
    "human-mediated.response-envelope.json",
    "ola-redaction.service-offer.json",
    "cpp-reasoning.service-offer.json",
    "orbiplex-core.topic-taxonomy.json",
    "resolved.topic-resolution.json",
    "ambiguous.topic-resolution.json",
    "unresolved.topic-resolution.json",
    "cpp-sort.corpus-reasoning-query.json",
    "accept.corpus-reasoning-bid.json",
    "decline.corpus-reasoning-bid.json",
    "fish-water.corpus-reasoning-answer.json",
    "active.corpus-reasoning-bid-state.json",
    "private.corpus-reasoning-room-policy.json",
    "moderated.corpus-reasoning-chair-control-policy.json",
    "private.corpus-reasoning-room-policy-v2.json",
    "expert.corpus-reasoning-room-invite.json",
    "expert-contribution.corpus-reasoning-turn-proposal.json",
    "basic.service-offer-relay.json",
    "casualfeeders-breakfast-research.service-order.json",
    "basic.offer-catalog-fetch-request.json",
    "basic.offer-catalog-fetch-response.json",
    "personal-local.classification.json",
    "quarantined-ingress.classification.json",
    "personal-to-community-one-shot.classification.json",
    "community-to-public-persistent.classification.json",
    "write-entry.memarium-host-api.json",
    "inline-note.memarium-blob.json",
    "basic.whisper-redaction-prepare-request.json",
    "draft-ready.whisper-redaction-prepare-response.json",
    "email-dispatched.whisper-trace.json",
    "email-content.whisper-trace.json",
    "image-held.whisper-trace.json",
    "email-content.whisper-trace-consent-request.json",
    "email-dispatched.whisper-trace-publish-request.json",
    "accepted.whisper-trace-publish-result.json",
    "filesystem-retaliation.weak-signal-finding.json",
    "declassify.memarium-host-api.json",
    "revoked.memarium-host-api.json",
    "private-whisper.artifact-delivery-envelope.json",
    "contact-request-via-contact-lookup.artifact-delivery-envelope.json",
    "basic.artifact-object-pointer.json",
    "basic.middleware-channel-hello.json",
    "basic.middleware-channel-accepted.json",
    "request.middleware-channel-frame.json",
    "basic.middleware-channel-host-capability-call.json",
    "failed.middleware-channel-call-result.json",
    "basic.middleware-channel-request-cancel.json",
    "basic.middleware-channel-heartbeat.json",
    "basic.middleware-channel-session-shutdown.json",
    "basic.middleware-module-http-request.json",
    "basic.middleware-module-http-response.json",
    "accepted.artifact-delivery-result.json",
    "running.artifact-delivery-status.json",
    "basic.interaction-broker-watch.json",
    "file-exists.interaction-broker-wait.request.json",
    "satisfied.interaction-broker-wait.outcome.json",
    "terminal-alive.interaction-broker-probe.json",
    "production.sensorium-operational-context.json",
    "basic.sensorium-relative-path-address.json",
    "cargo-test.sensorium-command-profile.json",
    "basic.sensorium-command-intent.json",
    "laptop.sensorium-pty-resource-caps.json",
    "local.sensorium-workbench-environment.json",
    "fixture.sensorium-virt-backend-capabilities.json",
    "fixture.sensorium-virt-environment-plan.json",
    "fixture.sensorium-virt-image-manifest.json",
    "ready.sensorium-virt-recovery-record.json",
    "handshake.sensorium-virt-guest-frame.json",
    "request.sensorium-virt-guest-frame.json",
    "fixture.sensorium-virt-host-request.json",
    "invoke.sensorium-virt-host-request.json",
    "passed.sensorium-virt-vfkit-deployment-report.json",
    "passed.sensorium-virt-cloud-hypervisor-deployment-report.json",
    "passed.story-012-vfkit-full-system-report.json",
    "running.sensorium-terminal-session.json",
    "cargo.sensorium-terminal-command.json",
    "operator.sensorium-terminal-input.json",
    "stdout.sensorium-terminal-event.json",
    "terminal.sensorium-interface-remote-feed-request.json",
    "viewport.sensorium-terminal-screen-snapshot.json",
    "tree.sensorium-file-snapshot.json",
    "inline.sensorium-file-read-result.json",
    "unified.sensorium-workbench-patch.json",
    "applied.sensorium-workbench-patch-apply-result.json",
    "staged.sensorium-workbench-patch-stage-result.json",
    "completed.sensorium-workbench-outcome.json",
    "active.sensorium-interface-subscription-status.json",
    "published.sensorium-interface-status.json",
    "renew.sensorium-interface-subscription-command.json",
    "temperature.sensorium-interface-descriptor.json",
    "temperature.sensorium-interface-frame.json",
    "temperature.sensorium-interface-read-request.json",
    "temperature.sensorium-interface-read-result.json",
    "temperature.sensorium-interface-subscribe-request.json",
    "push-inline.inac-control.json",
    "refused.inac-control.json",
    "invite-only.contact-claim.json",
    "invitation-required.contact-lookup-result.json",
    "no-match.contact-lookup-result.json",
    "basic.local-contact.json",
    "basic.contact-attestation-request.json",
    "issued.contact-attestation-result.json",
    "community-basic.membership-invitation.json",
    "community-basic.membership-sponsorship.json",
    "probationary.membership-acceptance.json",
    "newcomer.participant-entry-profile.json",
    "newcomer.participant-effective-limits.json",
    "default.surface-access-policy.json",
    "basic.room.json",
    "grant-member.room-membership.json",
    "close.room-event.json",
    "closed-private.room-policy.json",
    "basic.room-live-message.json",
    "reply.room-live-message-v2.json",
    "deny.room-access-denial.json",
    "moderated.room-floor-policy.json",
    "assigned.room-floor-lease.json",
    "mute.room-moderation-intent.json",
    "admitted.room-moderation-audit.json",
    "member.room-relay-endpoint.json",
    "federation.room-relay-endpoint.json",
    "basic.room-relay-delivery.json",
    "basic.room-relay-sender-key-distribution.json",
    "basic.room-relay-sealed-delivery.json",
    "member.room-membership-attestation.json",
    "member-self.room-membership-attestation-request.json",
    "issued.room-attestation-audit.json",
    "refused.room-attestation-audit.json",
    "messaging.contact-request.json",
    "basic.message-envelope.json",
    "issued.messaging.passport-issued.json",
    "public-seed-directory.service-ca-material.json",
    "public-seed-directory.service-ca-revocation.json",
    "basic.causal-context.json",
    "completed.execution-receipt.json",
    "revocations.replication-summary.json",
    "revocations.replication-delta-request.json",
    "revocations.replication-delta-batch.json",
    "partial.replication-apply-report.json",
    "room-membership.scoped-claim-request.json",
    "room-membership.scoped-claim-presentation.json",
    "initial.scoped-claim-type-registry.json",
    "scheduler.trace-event.json",
    "scheduler.trace-link.json",
    "accepted.corpus-reasoning-role-assignment.json",
    "accepted.corpus-reasoning-instruction-overlay.json",
)

INVALID_EXAMPLE_WHITELIST = (
    "plain-ws.room-relay-endpoint.json",
    "member-placement.room-relay-sealed-endpoint.json",
    "session-bearer.room-relay-delivery.json",
    "unscoped-delegation.room-event.json",
    "missing-storage-ref.node-identity.json",
    "inline-secret.node-identity.json",
    "no-endpoints.node-advertisement.json",
    "missing-new-proof.node-succession.json",
    "ack-without-reference.peer-handshake.json",
    "no-core-caps.capability-advertisement.json",
    "org-without-custody.federation-root.json",
    "unknown-field.federation-root.json",
    "unsigned.federation-root.json",
    "bad-inline-endorsement.federation-root.json",
    "official-flag.federation-root.json",
    "missing-enabled.federation-root.json",
    "bad-seed-directory-tls-pin.federation-root.json",
    "missing-grants.capability-authorization-policy.json",
    "wrong-kind.signal-marker-envelope.json",
    "raw-with-operations.signal-marker.json",
    "conflict-without-category.coi-declaration.json",
    "high-risk-without-approvals.exception-record.json",
    "critical-without-monitoring-metrics.exception-record.json",
    "system-requester-with-non-system-id.exception-record.json",
    "wrong-policy-id.exception-record.json",
    "bad-source-node-id.emergency-signal.json",
    "unknown-trigger-class.emergency-signal.json",
    "tc5-without-flag.emergency-signal.json",
    "tc5-flag-on-non-tc5.emergency-signal.json",
    "nym-procedural-governance-inaction.reputation-signal.json",
    "zero-weight.reputation-signal.json",
    "neutral-polarity.reputation-signal.json",
    "participant-kind-with-node-id.reputation-signal.json",
    "council-emitter-without-council-id.reputation-signal.json",
    "org-root-without-custody.agora-authority-policy.json",
    "detailed-public-rejection.agora-public-rejection.json",
    "runtime-authority.reputation-snapshot.json",
    "negative-price.procurement-offer.json",
    "no-confirmation-paid.procurement-contract.json",
    "settled-without-payee.procurement-receipt.json",
    "corpus-reasoning-role-assignment-widening.json",
    "missing-content.corpus-reasoning-turn-proposal.json",
    "unknown-field.corpus-reasoning-turn-proposal.json",
    "wrong-turn-id-prefix.corpus-reasoning-turn-proposal.json",
    "corpus-reasoning-instruction-overlay-ambient.json",
    "gateway-policy-with-participant-operator.gateway-policy.json",
    "escrow-policy-without-operator.escrow-policy.json",
    "incident-without-basis.settlement-policy-disclosure.json",
    "manual-review-without-decision-basis.settlement-policy-disclosure.json",
    "community-pool-without-council-controller.ledger-account.json",
    "inbound-topup-without-fee-breakdown.gateway-receipt.json",
    "without-basis.community-pool-disbursement.json",
    "missing-via-node.participant-bind.json",
    "mixed-participant-and-nym.question-envelope.json",
    "private-scope-public-delivery.question-envelope.json",
    "selected-responder-missing-federation.question-envelope.json",
    "human-flag-without-human-origin.response-envelope.json",
    "corpus-provider-missing-taxonomy.service-offer.json",
    "min-price-above-max.corpus-reasoning-query.json",
    "accept-without-offer.corpus-reasoning-bid.json",
    "counter-without-offer.corpus-reasoning-bid.json",
    "decline-with-offer.corpus-reasoning-bid.json",
    "non-did-taxonomy-issuer.service-offer.json",
    "blocked-core-messaging.participant-capability-limits.json",
    "missing-scopes.membership-sponsorship.json",
    "guest-with-broadcast.participant-entry-profile.json",
    "unknown-surface.surface-access-policy.json",
    "missing-participant-bind.client-instance-attachment.json",
    "missing-participant-bind.client-instance-detachment.json",
    "missing-detachment-ref.client-instance-recovery.json",
    "direct-personal-to-public.classification.json",
    "one-shot-with-expires.classification.json",
    "persistent-without-expires.classification.json",
    "public-with-full-subjects.classification.json",
    "success-without-draft.whisper-redaction-prepare-response.json",
    "inline-without-consent.whisper-trace.json",
    "digest-only-with-content.whisper-trace.json",
    "direct-with-hops.whisper-trace.json",
    "raw-source.weak-signal-finding.json",
    "review-not-required.weak-signal-finding.json",
    "grant-without-grants.room-membership.json",
    "mediated-policy-with-live.room-policy.json",
    "live-message-with-session-bearer.room-live-message.json",
    "duplicate-reply.room-live-message-v2.json",
    "reinstate-without-supersedes.room-access-denial.json",
    "unknown-mode.room-floor-policy.json",
    "expiry-on-mute.room-moderation-intent.json",
    "widened.corpus-reasoning-chair-control-policy.json",
    "missing-policy-ref.corpus-reasoning-room-policy-v2.json",
    "inac-push-missing-artifact.inac-control.json",
    "raw-handle.contact-lookup.artifact-delivery-envelope.json",
    "unsupported-mode.contact-lookup.artifact-delivery-envelope.json",
    "missing-store-ref.artifact-object-pointer.json",
    "unknown-field.middleware-channel-hello.json",
    "zero-epoch.middleware-channel-accepted.json",
    "response-with-request-id.middleware-channel-frame.json",
    "caller-override.middleware-channel-host-capability-call.json",
    "succeeded-with-failure.middleware-channel-call-result.json",
    "missing-target.middleware-channel-request-cancel.json",
    "unknown-field.middleware-channel-heartbeat.json",
    "missing-deadline.middleware-channel-session-shutdown.json",
    "traversal.middleware-module-http-request.json",
    "query-in-path.middleware-module-http-request.json",
    "header-injection.middleware-module-http-response.json",
    "traversal.interaction-broker-wait.request.json",
    "traversal.sensorium-relative-path-address.json",
    "latest-state-replay.sensorium-interface-descriptor.json",
    "unknown-class.sensorium-operational-context.json",
    "codepoint-overflow.sensorium-operational-context.json",
    "utf8-byte-overflow.sensorium-operational-context.json",
    "unknown-isolation.sensorium-virt-backend-capabilities.json",
    "unknown-network.sensorium-virt-environment-plan.json",
    "missing-sbom.sensorium-virt-image-manifest.json",
    "quarantined-without-reason.sensorium-virt-recovery-record.json",
    "zero-chunks.sensorium-virt-guest-frame.json",
    "legacy-operation.sensorium-virt-guest-frame.json",
    "unknown-operation.sensorium-virt-host-request.json",
    "unknown-guest-operation.sensorium-virt-host-request.json",
    "non-patch-transfer.sensorium-virt-host-request.json",
    "missing-patch-transfer.sensorium-virt-host-request.json",
    "over-budget.sensorium-virt-vfkit-deployment-report.json",
    "over-budget.sensorium-virt-cloud-hypervisor-deployment-report.json",
    "duplicate-check.story-012-vfkit-full-system-report.json",
    "one-shot-with-subscription.sensorium-interface-read-request.json",
    "ready-with-reason.sensorium-interface-status.json",
    "snapshot-with-payload-and-artifact.sensorium-interface-frame.json",
    "terminal-one-shot.sensorium-interface-read-result.json",
    "missing-bytes.sensorium-terminal-event.json",
    "input-content.sensorium-terminal-event.json",
    "status-with-output.sensorium-terminal-event.json",
    "over-limit.sensorium-interface-remote-feed-request.json",
    "invitation-without-route.contact-lookup-result.json",
    "missing-signature.message-envelope.json",
    "memarium-blob-without-signature.memarium-blob.json",
    "no-scope.service-ca-material.json",
    "missing-endorser.federation-service-endorsement.json",
    "unsupported-artifact.capability-proof-presentation-batch.json",
    "missing-signature.seed-directory-query-attestation.json",
    "too-many-parents.causal-context.json",
    "unknown-field.causal-context.json",
    "payload.execution-receipt.json",
    "bad-cursor.replication-summary.json",
)

GOLDEN_WHITELIST = (
    "golden-room-projection-input.json",
    "golden-room-projection-output.json",
    "middleware-channel-v1.golden.json",
    "sensorium-actuation-relative-path.v1.json",
)

SCHEMA_GATE_AGORA_SCHEMA_WHITELIST = (
    "seed-capability-registration.v1.schema.json",
    "service-offer.v1.schema.json",
    "topic-taxonomy.v1.schema.json",
    "topic-resolution.v1.schema.json",
    "corpus-reasoning-bid.v1.schema.json",
    "corpus-reasoning-answer.v1.schema.json",
    "corpus-reasoning-chair-control-policy.v1.schema.json",
    "corpus-reasoning-room-policy.v1.schema.json",
    "corpus-reasoning-room-policy.v2.schema.json",
    "corpus-reasoning-room-invite.v1.schema.json",
    "corpus-reasoning-turn-proposal.v1.schema.json",
    "room.v1.schema.json",
    "room-membership.v1.schema.json",
    "room-event.v1.schema.json",
    "room-policy.v1.schema.json",
    "room-live-message.v1.schema.json",
    "room-live-message.v2.schema.json",
    "room-access-denial.v1.schema.json",
    "room-floor-policy.v1.schema.json",
    "room-floor-lease.v1.schema.json",
    "room-moderation-intent.v1.schema.json",
    "room-moderation-audit.v1.schema.json",
    "room-relay-endpoint.v1.schema.json",
    "room-relay-delivery.v1.schema.json",
    "room-relay-sender-key-distribution.v1.schema.json",
    "room-relay-sealed-delivery.v1.schema.json",
    "room-membership-attestation.v1.schema.json",
    "room-membership-attestation-request.v1.schema.json",
    "room-attestation-audit.v1.schema.json",
    "whisper-trace.v1.schema.json",
)


def copy_files(files: tuple[str, ...], source_dir: Path, target_dir: Path) -> None:
    target_dir.mkdir(parents=True, exist_ok=True)
    for name in files:
        source = source_dir / name
        target = target_dir / name
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)


def copy_shared_schemas(schema_target: Path) -> None:
    shared_source = SCHEMAS_DIR / "_shared"
    if not shared_source.exists():
        return
    shared_target = schema_target / "_shared"
    shared_target.mkdir(parents=True, exist_ok=True)
    for source in shared_source.rglob("*.json"):
        relative = source.relative_to(shared_source)
        target = shared_target / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)


def resolve_node_root(node_src: str) -> Path:
    """Resolve and validate the Node workspace root before writing contracts."""
    node_root = (ROOT / node_src).resolve()
    if node_root.parts[-2:] == ("protocol", "contracts"):
        raise ValueError(
            "--node-src must name the Node workspace root, not its protocol/contracts directory"
        )
    missing = [
        str(relative)
        for relative in NODE_WORKSPACE_SENTINELS
        if not (node_root / relative).is_file()
    ]
    if missing:
        raise ValueError(
            f"--node-src does not name a Node workspace root; missing: {', '.join(missing)}"
        )
    return node_root


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--node-src", default="../node")
    args = parser.parse_args()

    try:
        node_root = resolve_node_root(args.node_src)
    except ValueError as error:
        parser.error(str(error))
    contracts_root = node_root / "protocol" / "contracts"
    schema_target = contracts_root / "schemas"
    example_target = contracts_root / "examples"
    invalid_target = example_target / "invalid"
    golden_target = contracts_root / "golden"
    schema_gate_agora_target = node_root / "schema-gate" / "contracts" / "schemas" / "agora"

    copy_files(SCHEMA_WHITELIST, SCHEMAS_DIR, schema_target)
    copy_shared_schemas(schema_target)
    copy_files(SCHEMA_GATE_AGORA_SCHEMA_WHITELIST, SCHEMAS_DIR, schema_gate_agora_target)
    copy_files(EXAMPLE_WHITELIST, EXAMPLES_DIR, example_target)
    copy_files(INVALID_EXAMPLE_WHITELIST, INVALID_EXAMPLES_DIR, invalid_target)
    copy_files(GOLDEN_WHITELIST, GOLDEN_DIR, golden_target)
    shutil.copy2(
        SCHEMAS_DIR / "registries" / "vendor-media-types.v1.json",
        contracts_root / "vendor-media-types.v1.json",
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
